// generated by stringer -type=Cursor; DO NOT EDIT

package cursor

import "fmt"

const _Cursor_name = "DefaultAliasAllScrollAutoCellContextMenuColResizeCopyCrossHairEResizeEWResizeGrabGrabbingHelpMoveNResizeNEResizeNESWResizeNSResizeNWResizeNWSEResizeNoDropNoneNotAllowedPointerProgressRowResizeSResizeSEResizeSWResizeTextVerticalTextWResizeWaitZoomInZoomOutInitialInherit"

var _Cursor_index = [...]uint16{0, 7, 12, 21, 25, 29, 40, 49, 53, 62, 69, 77, 81, 89, 93, 97, 104, 112, 122, 130, 138, 148, 154, 158, 168, 175, 183, 192, 199, 207, 215, 219, 231, 238, 242, 248, 255, 262, 269}

func (i Cursor) String() string {
	if i < 0 || i+1 >= Cursor(len(_Cursor_index)) {
		return fmt.Sprintf("Cursor(%d)", i)
	}
	return _Cursor_name[_Cursor_index[i]:_Cursor_index[i+1]]
}
